cul-it/mann-wagon

app/views/pages/index.liquid.haml
public/stylesheets/base/_cul-brand.scss

Via Typekit, as per latest direction from Mann Design Task Force.

MANNWEB-239 P22 Underground font

---

app/views/pages/search.liquid
app/views/snippets/header.liquid.haml

Accounting for differences between serving site on Wagon and Engine. #112

Minor tweaks to site-search

---

app/content_types/spaces.yml
app/content_types/spaces_study_types.yml
app/content_types/spaces_types.yml
app/views/pages/use/spaces.liquid
data/spaces_study_types.yml

Refactoring for Find a Space #174

Spaces remix

---

app/content_types/spaces.yml
app/content_types/spaces_study_types.yml

Further tweaking of spaces

---

app/views/pages/index.liquid.haml
public/stylesheets/components/_available-now.scss

Spaces consistency on home page

---

app/views/pages/search.liquid

Ensuring that we're good to go for a final scrape/index build prior to usability
testing tomorrow. See #173.
We now have 85 indexed pages, up from 63.

Update site search to use latest scrape

---

app/views/pages/index.liquid.haml
app/views/pages/news-events/events.liquid.haml
public/stylesheets/components/_available-now.scss
public/stylesheets/components/_featured.scss
public/stylesheets/pages/_home.scss

Home cleanup

---

app/views/pages/index.liquid.haml
public/stylesheets/components/_available-now.scss

Low hanging tweaks based on feedback, comments and observed behavior during first round of usability testing (4/21/16).

Usability 1 quickies

---

app/views/pages/index.liquid.haml
public/stylesheets/components/_available-now.scss
public/stylesheets/components/_events-home.scss
public/stylesheets/components/_guides.scss
public/stylesheets/pages/_home.scss
public/stylesheets/pages/_hours.scss

Usability feedback - prominence (round 1)

---

app/views/pages/index.liquid.haml
app/views/snippets/header.liquid.haml
public/stylesheets/components/_available-now.scss
public/stylesheets/components/_events-home.scss

Based on feedback and observed patterns of user behavior during first round of
usability testing on 4/21/16.
See #203 for details.

More links on home page

---

app/views/pages/index.liquid.haml
app/views/pages/news-events/events.liquid.haml
public/javascripts/events.js

Takes care of #181, #134, #178

Vue events

---

app/views/snippets/section-nav.liquid.haml
public/stylesheets/components/_section-nav.scss

Ensure section-nav can handle the full depth of the IA for the new site. #244

For the children

---

app/views/snippets/primary-nav.liquid
public/stylesheets/_config.scss
public/stylesheets/layout/_nav.scss

Minor improvements and bug fixes to mega menu.
#238, #241

Mega tweak

---

app/content_types/departments.yml
app/content_types/divisions.yml
app/content_types/service_desks.yml
app/content_types/staff.yml

Plus foundation for liaison & experts feature. #197 #236.

Staff directory

---

app/views/pages/index.liquid.haml
app/views/snippets/avail-now-study.liquid

Use a snippet (adios Haml) & DRY it up for #224. As promised in 1c60ba2 & #203.
Availability is harcoded to always available for the moment. Will be addressed
with #255, #256, & #261.

Iterate on spaces content type for available-now

---

app/views/pages/layouts/default.liquid.haml
app/views/snippets/spaces-cards.liquid
public/javascripts/spaces-popup.js
public/stylesheets/components/_space-finder.scss

Spaces evolve

---

app/views/pages/layouts/default.liquid.haml
app/views/pages/search.liquid
public/stylesheets/components/_page-content.scss

Head start on #173 in case things get nuts Wednesday morning ;)

Update to latest scrape (aka search index)

---

app/views/snippets/spaces-cards.liquid
public/stylesheets/components/_space-finder.scss

Loanable deets

---

app/views/pages/use/spaces.liquid
app/views/pages/use/spaces/content_type_template.liquid
app/views/snippets/spaces-cards.liquid
public/stylesheets/components/_space-finder.scss

Spaces photos

---

app/views/pages/use/spaces/content_type_template.liquid
app/views/snippets/avail-now-study.liquid
app/views/snippets/room-availability-logic.liquid
app/views/snippets/room-availability-variables.liquid
app/views/snippets/spaces-cards.liquid
config/metafields_schema.yml

Addresses #255, #261  
- Room availability from Libcal and Mannservices, all booked rooms are always available for now
- Next available option only for today
- Only using group rooms from Mannservices, not small and large group rooms
- Only using one of the collaborative workstations

Room availability

---

app/views/pages/use/spaces.liquid
app/views/pages/use/spaces/all/content_type_template.liquid
app/views/pages/use/spaces/content_type_template.liquid
app/views/snippets/booked-modal.liquid
app/views/snippets/spaces-cards.liquid
public/stylesheets/components/_space-finder.scss
public/stylesheets/components/_space.scss
public/stylesheets/main.scss

Template for individual space view

---

app/views/pages/search.liquid

In prep for round 2 of usability testing. #173

Switch to latest scrapinghub job for search index

---

app/content_types/purchase_requests.yml
app/views/pages/layouts/default.liquid.haml
app/views/pages/request-a-purchase.liquid
public/javascripts/purchase-request-validation.js

Purchase form

---

app/views/pages/404.liquid.haml
app/views/pages/about/staff.liquid
app/views/pages/about/staff/divisions/content_type_template.liquid
app/views/pages/index.liquid.haml
app/views/pages/layouts/default.liquid.haml
app/views/pages/layouts/landing.liquid.haml
app/views/pages/layouts/section.liquid.haml
app/views/pages/news-events/events.liquid.haml
app/views/pages/projects.liquid.haml
app/views/pages/projects/content_type_template.liquid.haml
app/views/pages/request-a-purchase.liquid
app/views/pages/search.liquid
app/views/pages/use/spaces.liquid
app/views/pages/use/spaces/all/content_type_template.liquid
app/views/pages/use/spaces/content_type_template.liquid
public/stylesheets/components/_page-content.scss

Spun off from a need that arose while working on #318.

Nested blocks & consistency for layouts

---

Gemfile
Gemfile.lock
app/content_types/site_feedback.yml
app/views/pages/contact.liquid
app/views/pages/contact/site-feedback.liquid
app/views/snippets/footer.liquid.haml
app/views/snippets/form-site-feedback.liquid
src/js/form-site-feedback.js
src/scss/components/_mann-form.scss
src/scss/main.scss
webpack.config.js

Site feedback

---

app/views/pages/index.liquid.haml
app/views/snippets/availnow-study.liquid

Homepage rapidfire

---

app/views/pages/use/spaces/all/content_type_template.liquid
app/views/snippets/modal-libcal.liquid
app/views/snippets/spaces-cards.liquid
src/js/modal-libcal.js
webpack.config.js

Libcal iframe

---

app/views/snippets/primary-nav.liquid
data/spaces_types.yml

Spaces megamenu

---

app/content_types/spotlights.yml

Spotlight content type

---

app/content_types/news.yml

News content type

---

app/views/pages/hours.liquid.haml
src/js/hours-nav.js
src/scss/pages/_hours.scss

See the preview widget code in LibCal for styling information.

Monthly view widget for LibCal hours.

---

app/content_types/instruction_requests.yml
app/views/snippets/form-instruction-request.liquid
src/js/form-instruction-request.js

Final (almost) tweaks to instruction request form

---

app/content_types/consultations.yml
app/content_types/instruction_requests.yml
app/views/snippets/form-consultation-request.liquid
app/views/snippets/form-instruction-request.liquid

Primarily addresses server-side validation, with the exception of correcting the field type for the 3rd date preference on the instruction request form.

Form validation cleanup

---

app/views/pages/layouts/section.liquid
app/views/snippets/landing.liquid

#525 is all about consistency. Follow mega menu's lead from #510.

Test listed & published status for layouts

---

app/views/pages/index.liquid.haml
app/views/pages/news-events/events/upcoming.liquid
config/metafields_schema.yml
package.json
vue/events/events-page/components/Events.vue
vue/events/events-page/directives/datepicker-directive.js
vue/events/events-page/templates/events-template.html
vue/events/homepage-events/components/HomepageEvents.vue
vue/events/homepage-events/templates/homepage-template.html

Integrate r25 events.
Using site metafields for default events.
Some text and filter button changes.

Events r25

---

app/views/snippets/homepage.liquid
config/metafields_schema.yml
config/site.yml
vue/events/events-page/components/Events.vue
vue/events/homepage-events/components/HomepageEvents.vue

Addresses #511, Fixes #536, #545, #534

Event fixes

---

src/scss/components/_page-content.scss

First crack at chipping away the list in #79.

Wysihtml styles

---

app/views/pages/news-events/events/upcoming.liquid
app/views/snippets/events-app.liquid
app/views/snippets/homepage.liquid
vue/events/events-page/components/Events.vue
vue/events/events-page/events-page.js
vue/events/events-page/templates/events-template.html
vue/events/homepage-events/components/HomepageEvents.vue
vue/events/homepage-events/templates/homepage-template.html

Addresses #506 #551 and fixed bugs #562 #563

Events path

---

app/views/snippets/dynamic-course-reserves.liquid
src/scss/components/course-reserves.scss

Course reserves table

---

app/content_types/event_locations.yml
app/content_types/event_types.yml
app/views/snippets/events-app.liquid
app/views/snippets/homepage.liquid
vue/events/events-page/components/Events.vue
vue/events/events-page/directives/datepicker-directive.js
vue/events/events-page/templates/events-template.html
vue/events/homepage-events/components/HomepageEvents.vue
vue/events/homepage-events/templates/homepage-template.html

Events curated filters

---

app/views/snippets/availnow-study.liquid
app/views/snippets/homepage.liquid
app/views/snippets/spaces-cards.liquid
src/js/spaces-quiet.js
src/scss/components/_available-now.scss
src/scss/components/_space-finder.scss
src/scss/main.scss
webpack.config.js

See #440 and #501, plus a little bonus:
* For unavailable study spaces on the homepage, show next available on hover via SUI popover component

Today at Mann tweaks

---

app/content_types/spaces.yml
app/views/pages/use/spaces/all/content_type_template.liquid
app/views/snippets/room-availability-logic.liquid
app/views/snippets/room-availability-next.liquid
app/views/snippets/spaces-cards.liquid

Missing spaces.yml, should have been part of #573

Advance reservations

---

app/views/pages/layouts/default.liquid
app/views/snippets/header.liquid
app/views/snippets/site-search.liquid
src/scss/components/_site-search.scss

Quick first iteration of #509 via #577

Site Search via Google CSE

---

app/views/snippets/site-search.liquid
src/scss/components/_site-search.scss

Iterate search results style and behavior

---

app/views/pages/use/spaces/all/content_type_template.liquid
app/views/pages/use/spaces/content_type_template.liquid
app/views/snippets/spaces-cards.liquid
app/views/snippets/spaces-reservable-button.liquid
app/views/snippets/spaces-subnav.liquid
src/js/spaces-cards.js
src/scss/components/_space-finder.scss
webpack.config.js

Mostly about #590 & #591. Also a little bonus with a new icon for quiet study spaces.

Overhaul to Find a Space cards

---

app/content_types/spotlights.yml
app/views/snippets/spotlights-carousel.liquid

This almost finalizes the spotlight feature (#361), sans #478.

Spotlight improvements

---

Gemfile
Gemfile.lock

Which in turn depends on latest steam `1.2.0.rc2`.

Bump to latest wagon 2.2.0.rc2

---

src/scss/components/_events.scss
vue/events/events-page/events-page.js
vue/events/events-page/templates/events-template.html

Prominent event filters

---

app/views/snippets/footer.liquid
src/scss/_config.scss
src/scss/components/_cu-banner.scss
src/scss/components/_search.scss
src/scss/components/_todays-hours.scss
src/scss/layout/_footer.scss
src/scss/layout/_nav.scss

Address bugs and feedback after applying color palette

---

app/content_types/event_locations.yml
app/content_types/event_types.yml
app/content_types/reservation_systems.yml
app/content_types/spaces.yml
app/views/pages/use/spaces/all/content_type_template.liquid
app/views/snippets/modal-libcal.liquid
app/views/snippets/spaces-cards.liquid
app/views/snippets/spaces-reservable-button.liquid

* spaces #442 
* reservation systems #592 
* curated event locations #611

Content type adjustments 

---

app/views/snippets/spaces-cards.liquid

Maybe would have caught this sooner as part of #442 if there was better truthy/falsy consistency
between engine and wagon...

Logic tweak for spaces note

---

webpack.config.js

Speaking of stragglers/holdouts...doh. Should have been included with 42f3e1b.

Purge webpack config of purchase request form

---

app/views/pages/.gitignore
app/views/pages/site-feedback.liquid
app/views/snippets/footer.liquid

Adios contact us

---

src/scss/components/_events-home.scss
vue/events/homepage-events/templates/homepage-template.html

An improvement to the equal height events groupings from 4703c70 for #612.

Keep more link at bottom of events-home container

---

app/views/pages/use/spaces/all/content_type_template.liquid
app/views/pages/use/spaces/content_type_template.liquid
app/views/snippets/spaces-cards.liquid
app/views/snippets/spaces-reservable-button.liquid
app/views/snippets/staff-directory-body-grid.liquid
app/views/snippets/staff-directory-options.liquid

In the aftermath of 95f2b77 for #626. Hat tip to Tobi for catching these
stragglers.
* pretty much all of the icons for space-finder
* all icons on staff directory page

More sui icon vs font awesome cleanup

---

app/views/snippets/spaces-subnav.liquid

Rely on Liquid's sort filter and not the developer ;)

Ensure custom spaces subnav is alpha sorted

---

app/views/snippets/accessory-desktops.liquid

As it always should have been...  #617

Render basement status only if closed

---

app/content_types/projects.yml
app/views/pages/projects.liquid
app/views/snippets/content-type-projects.liquid
app/views/snippets/projects-all.liquid
src/scss/components/_page-content.scss
src/scss/components/_projects.scss
src/scss/main.scss

Projects tweaks

---

app/views/snippets/form-software-request.liquid

Oversight while working on 7866eb1 as part of #686.

Management link for software requests

---

Gemfile
Gemfile.lock
app/content_types/spaces.yml
app/views/snippets/content-type-spaces.liquid
app/views/snippets/header.liquid
app/views/snippets/space-hours.liquid
app/views/snippets/spaces-cards.liquid

1. Updated ref to latest mann_liquid_extensions gem
2. Handle exceptions and string manipulations in liquid

All about spaces hours

---

app/views/snippets/homepage.liquid
app/views/snippets/meet-experts.liquid
app/views/snippets/staff-book-consultation.liquid
app/views/snippets/staff-directory-body-grid.liquid
app/views/snippets/staff-directory-body-table.liquid
src/scss/_config.scss
src/scss/components/_consultation.scss
src/scss/components/_staff-directory.scss
src/scss/components/meet-experts.scss
src/scss/main.scss

Experts cleanup

---

app/views/snippets/header.liquid
src/js/vendor/doubletaptogo/doubletaptogo.min.js
src/scss/layout/_nav.scss
webpack.config.js

Megamenu accessibility for touch devices

---

app/views/snippets/staff-book-consultation.liquid
src/scss/_config.scss
src/scss/components/_staff-directory.scss

As per tabby mcsara's request...essentially reverting this from #705:
https://github.com/cul-it/mann-wagon/pull/705/commits/253b78dc9a03c8907ff29ecf2918d2c1b7e693ad

Restore consultation button to ocean-green

---

app/views/pages/layouts/default.liquid
app/views/snippets/site-analytics.liquid
config/metafields_schema.yml
config/site.yml

Conditionally render tracking code.

Site meta fields for tracking id's from GA and Piwik.

---

app/views/pages/layouts/default.liquid
app/views/snippets/header.liquid
src/js/nav-search.js
src/scss/_config.scss
src/scss/components/_search.scss
src/scss/layout/_nav.scss
webpack.config.js

Mobile search & nav

---

app/views/snippets/beta-banner.liquid
app/views/snippets/footer.liquid
src/js/beta-banner.js
src/scss/components/beta-banner.scss
webpack.config.js

Beta banner

---

src/scss/components/beta-banner.scss

Responsive body padding for beta banner

---

app/views/snippets/daily-haiku.liquid
app/views/snippets/footer.liquid

Parse RSS feed from wordpress site (cached for 6hrs). #406

Daily Haiku

---

app/views/snippets/beta-banner.liquid

Can get pretty frustrating while developing ;)

No beta banner when serving site in Wagon

---

app/views/snippets/hours-all.liquid
src/scss/components/_page-content.scss
src/scss/pages/hours.scss

Cul hours link

---

app/views/snippets/hours-category.liquid

Anchors for category headings on hours page

---

app/views/pages/layouts/section.liquid
app/views/snippets/content-type-spaces.liquid
app/views/snippets/dynamic-news.liquid
app/views/snippets/header.liquid
app/views/snippets/nav-builder.liquid
app/views/snippets/nav-section-builder.liquid
app/views/snippets/section-nav.liquid
app/views/snippets/spaces-cards.liquid
vue/course-reserves/components/reserve-item.html

Open external links in new tab/window

---

app/views/snippets/content-type-spaces-types.liquid
app/views/snippets/spaces-cards.liquid
app/views/snippets/spaces-finder.liquid
src/scss/components/_space-finder.scss

Reservable study spaces grouping

---

app/views/snippets/dynamic-all-experts.liquid
src/scss/components/all-experts.scss

Stop fighting the good fight and succumb to the pressure. Missed that the last
PR #771 introduced sass compiling errors.

Wrap sui buttons component for susy layout

---

app/views/snippets/dynamic-all-experts.liquid
src/js/all-experts.js

When it rains it pours...
Refactor from last hotfix PR (#772) introduced this bug...what's next?

Fix the expert toggling logic
