cul-it/mann-wagon

README.md

Goes a long way to ensure the correct and expected version of wagon is
being used.
Also update syntax highlighter for code snippets to `bash` alias.

Update README to specify use of `bundle exec`

---

Gemfile
Gemfile.lock

Relevant diffs:
* [wagon rc5 --> rc6](https://github.com/locomotivecms/wagon/compare/6a30532...4cc0a47)
* [steam rc8 --> rc9](https://github.com/locomotivecms/steam/compare/v1.0.0.rc8...v1.0.0.rc9)
* [coal rc3 --> rc4](https://github.com/locomotivecms/coal/compare/v1.0.0.rc3...v1.0.0.rc4)

New releases of wagon(rc6), steam(rc9) & coal(rc4)

---

data/projects.yml

Projects content type defines URL field as required. This was preventing a `wagon deploy -d` (deploying data).
Also clipped trailing slash from existing URLs for other projects.

Add URL for NYCCSC project

---

app/views/pages/search.liquid
app/views/snippets/header.liquid.haml
config/metafields_schema.yml
public/javascripts/search-select.js
public/stylesheets/components/_site-search.scss
public/stylesheets/main.scss

Using the `consume` tag and no filtering happening just yet. Lodash is up next
but for now any search term will return all results.
Didn't want to commit the API key for scrapinghub, so I decided to experiment
with the new metafields feature that's upcoming with v3.1. Very nice...very
nice...

Initial go at template for site search

---

Gemfile
Gemfile.lock

Just released yesterday, 4/21/16. Also includes latest steam v1.1.0 as
dependency.

Update to wagon v2.1.0

---

.gitignore
public/javascripts/eventsPage.bundle.js
public/javascripts/homePageEvents.bundle.js
webpack.config.js

No longer necessary since Vue and rest of JS are not being vendorized now thanks
to vue-loader (#313) and webpack.

Unignore public/javascripts/vendor

---

package.json

This is the latest release that includes the merged PR for relative paths.

Update to vue-loader v8.5.1 as minimum

---

Gemfile
Gemfile.lock

This, in turn, depends on latest steam 1.2.0.rc1, which includes both of our
merged PRs:
* Authorization header for consume tag (locomotivecms/steam#67)
* Request referer in global drop (locomotivecms/steam#73)

Bump to latest wagon 2.2.0.rc1

---

app/views/snippets/nav-megamenu.liquid
src/scss/layout/_nav.scss

This is a very quick & simple first attempt to address the number one issue we
observed in multiple rounds of usability testing where users were inadvertently
triggering the megamenu as the moved the cursor past the top level pages in the
navigation. As described in #451.
This current implementation is problematic on touch devices, so rest assured
this is not the final approach.

Delay reveal of megamenu by 200ms & add down caret

---

app/views/pages/help/research-support/workshops.liquid
app/views/pages/layouts/section.liquid

Attempt to address the fallout that resulted in moving workshops in the site hierarchy, combined with a previous decision to track the stub of all pages. More details in 0ecc646.

Workshops nav shuffle

---

app/views/pages/layouts/default.liquid
package.json
src/scss/main.scss

My previous attempt to refactor the Font Awesome font handling in 3c4bbc0 was
too good to be true. Browser cache was spoofing expected functionality when
reality was far from it. I could go back to using copy-webpack-plugin, but that
would put us in the same spot with AppSpider scan #465.
So...keep it simple and go with the CDN until further notice. Should keep
everyone happy in the meantime.

Use Font Awesome CDN

---

app/content_types/spotlights.yml
app/views/snippets/spotlights-carousel.liquid
app/views/snippets/spotlights-looper.liquid

As defined in a comment on #495:
https://github.com/cul-it/mann-wagon/issues/495#issuecomment-251718010
* 5 active spotlights max
* 3 spotlights min
* If active spotlights < 3, supplement with fallback image(s) up to 3 total
* fallback images are capped at 3 max

Adjust logic for spotlights fallback

---

app/views/snippets/header.liquid
src/js/form-consultation-request.js
src/js/form-instruction-request.js
src/js/form-site-feedback.js
src/js/form-software-request.js
vue/events/events-page/events-page.js
webpack.config.js

To avoid collision with Font Awesome for the search bar on any page that was
importing the icon component (forms and events calendar). See #626.

Vendorize sui icon component

---

app/content_types/software_requests.yml
app/views/snippets/form-software-request.liquid

Continuation of #298
* platform_managed_list SHOULD NOT be required
* licenses field was tracking value of url field
* helps to include value for delivery field...whoops
* a little more personal with the thank you message

Last minute fixes for the software request form

---

vue/software-list/components/software-list.vue
vue/software-list/software-list.js

This is the key to the bug in #606 and the reason why I was not able to reliably
reproduce this is because when hosting the site on wagon, `$(window).load` would
trigger after the Vue component was updated, but in the opposite order when
hosting on engine. We can ensure the proper order by utilizing Vue's watch
method.

Apply stickyheaders after softwareList is created

---

app/views/snippets/spaces-reservable-button.liquid

Yet another example of the dev instance Engine evaluating an empty string as
truthy. #625

Second condition for LibCal reserve button logic

---

app/views/pages/.gitignore
app/views/pages/news-events/events/calendar.liquid

Path is now `/news-events/events/calendar`.

Sync move of events calendar from back-office

---

app/views/snippets/footer.liquid

Wagon had no issue with the slug, but Engine required the handle. Better choice
anyway, since the handle is actually unique ;)

Use handle for filtering about page via with_scope

---

app/views/snippets/dynamic-news.liquid
app/views/snippets/footer.liquid
app/views/snippets/social-media-links.liquid
src/scss/components/_news.scss

Forgot about the recent overhaul to the footer that set the social media icons
to white and missed this while quickly testing after the merge.
Quick followup for #468.

Explicit styles for social media on news page

---

app/views/snippets/spotlights-looper.liquid

Account for engine's bogus truthy/falsy eval once again. #570

Ensure spotlight is linked only if URL exists

---

app/views/pages/layouts/basic-page.liquid.haml
app/views/pages/layouts/primary-landing.liquid
app/views/pages/layouts/primary.liquid
app/views/pages/layouts/section.liquid

Pretty sure there's a bug in Engine/Steam that doesn't allow these to be
overriden with an empty string. #668

Drop all editable_text placeholders from layouts

---

app/views/snippets/availnow-computers-setup.liquid

Pretty sure the consume tag is tripping up on the presence of the `header_auth`
option, that I introduced in locomotivecms/steam#67, when caching is also
enabled. Working on debugging this, but in the meantime backing out caching so
we have labstats data for the beta site.
This reverts commit 33abd0d47ddfa990b43986379a3c8546dfbdae2a.

Temporarily disable caching for Labstats

---

app/views/snippets/room-availability-logic.liquid

Would be nice to show library's next open time as next available time for rooms,
but that't not currently delivered in a useable format (as a separate variable)
via the `mannlib_hours` drop. #388

Loanable rooms unavailable when we're closed

---

vue/software-list/components/software-list.html
vue/software-list/components/software-list.vue

Except for email kiosks, which are no longer included in the map. #610

Link software list headings to smartmap

---

app/content_types/event_locations.yml
app/content_types/event_types.yml

Makes the list easier to scan and manage in the back-office.

Sort event_locations & event_types by name

---

app/views/snippets/content-type-spaces-types.liquid

Addresses a bug introduced in #759.
Ideally, we would use the `reservation_system` field to filter but Engine chokes
because it's expecting a BSON objectid. I couldn't figure out an operator to use
on a relationship field that could simply test for existence of relationship, so
falling back to test for the existence of the `reserve_sys_id` field via the
`gt` operator since it's an integer field.
Awkward, but works no matter whether the site is served by Wagon or Engine.
List of operators for `with_scope` tag:
https://github.com/locomotivecms/steam/blob/master/lib/locomotive/steam/liquid/tags/with_scope.rb#L19

Hotfix - filter reservable spaces for Engine

---

src/scss/components/_events.scss
src/scss/components/_page-content.scss
vue/events/events-page/components/Events.vue
vue/events/events-page/directives/datepicker-directive.js
vue/events/events-page/events-page.js
vue/events/events-page/templates/events-template.html

We temporarily disabled the R25 feed in #719 because the academic courses were overwhelming the events calendar. Our plan for re-introducing it back into the wild was hinted at in #720, but here it is again in more detail:
* add a toggle at the top of the Events Calendar, which is disabled by default (academic courses are **not rendered**)
* refactor `HomepageEvents.vue` so it ignores R25 data altogether (it should not include R25 as a data source)
* stick with the **Instruction** event type for R25, which we have already curated to **Academic Course**
* we've agreed that we will not include any additional alternate names for this curated event type to avoid mixing R25 data with any other data source
* if a user selects the **Academic Course** event type filter, this will also …

The return of R25

---

app/views/snippets/staff-book-consultation.liquid
app/views/snippets/staff-directory-body-grid.liquid
app/views/snippets/staff-directory-body-table.liquid

Turns out this never worked properly on the staff directory due to having the
consultation button for each staff member rendered two times due to the two
views (grid vs table) -- the table is hidden via JS on page load, but the
duplication of IDs caused only the first button in the DOM (the table) to work.
Ensuring unique IDs for the buttons addressed this problem.

Libcal widget works in both views of staff dir
